### ISSUE TITLE
Struct fields - tracking issue

### ISSUE THREAD

**Issue by VonTum** [pc2/sus-compiler#8]
Relates to #2. 

To add struct fields, there's a few prerequisites

- [] Use hindley-milner type inference (needs to be done regardless)
- [] Fields and interface names are resolved at typechecking time (this means removing them from initialization.rs)
- [] Flattened representation of fields
- [] Instantiate representation of fields
- [] Codegen for structs & fields
